/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountryChar123SubdivisionChar125RouteImport } from './routes/$country.{-$subdivision}'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryChar123SubdivisionChar125Route =
  CountryChar123SubdivisionChar125RouteImport.update({
    id: '/$country/{-$subdivision}',
    path: '/$country/{-$subdivision}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$country/{-$subdivision}': typeof CountryChar123SubdivisionChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$country/{-$subdivision}': typeof CountryChar123SubdivisionChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$country/{-$subdivision}': typeof CountryChar123SubdivisionChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$country/{-$subdivision}'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$country/{-$subdivision}'
  id: '__root__' | '/' | '/$country/{-$subdivision}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountryChar123SubdivisionChar125Route: typeof CountryChar123SubdivisionChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$country/{-$subdivision}': {
      id: '/$country/{-$subdivision}'
      path: '/$country/{-$subdivision}'
      fullPath: '/$country/{-$subdivision}'
      preLoaderRoute: typeof CountryChar123SubdivisionChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountryChar123SubdivisionChar125Route: CountryChar123SubdivisionChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
